### ISSUE TITLE
Solved! It's just about the version of JDK

### ISSUE THREAD

**Issue by Toddy101** [NetLogo/Sample-Extension#1]
This is my first to write the Netlogo extension.Many thanks for your help.

I do as the steps on the webpage "Extensions API:Writing Extensions" and I copyed you code here.

The former steps seems correctly,and "example.jar" was created successfully.But the last step went wrong ,which is "Use your extension in a model".To be specific,I wrote the code "extensions [example]" in the code page of Netlogo 5.1.0,when I moved the cursor to the main page ,then comes the ERROR WINDOW,the information as follows:

NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

java.lang.UnsupportedClassVersionError: SampleExtension : Unsupported major.minor version 52.0
 at java.lang.ClassLoader.defineClass1(Native Method)
 at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
 at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
 at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
 at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
 at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
 at java.net.URLClassLoader$1.run(URLClassLoader.java:197)

**Comment by SethTisue** [comment]
yup, this is as documented at https://github.com/NetLogo/NetLogo/wiki/Extensions-API
